In [6]:
import numpy as np

In [7]:
input = np.array([[0, 0, 1, 1], [1, 1, 1, 1],[1, 0, 1, 1],[0, 1, 1, 1]])

print(input)
print(len(input))

[[0 0 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]]
4


In [8]:
output = np.array([0, 1, 1, 0])

print(output)

[0 1 1 0]


In [9]:
def perceptron(input, output, epoch):
    
    #initialize weights
    weight = np.zeros(len(input))
    netarray = np.ones(len(output)) 

    #learning rate c=1
    c= 1
    
    ctr = 0 
    
    while ctr < epoch:
        
        for j in range(len(input)):
            
            #calculate x.w
            totalinp = np.dot(input[j],weight)
            
            if(totalinp > 0):
                net = 1
            else:
                net = 0
            netarray[j] = net
            
            #calculate delta w
            for k in range(len(weight)):
                weight[k] = weight[k] + (c * (output[j] - net) * input[j][k])
            
        ctr = ctr + 1
            
    return weight, netarray

In [10]:
#running for 2 epochs
perceptron(input,output,2)

#output is weight and net input at the end of the iterations


(array([1., 0., 0., 0.]), array([0., 1., 1., 0.]))